# Generated by Django 4.1.3 on 2022-12-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='user',
            name='_profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
