# Generated by Django 4.1.3 on 2022-12-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_user_profile_img_user__profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_profile_img',
            new_name='profile_img',
        ),
    ]
